# To validate it, run: docker compose config
# docker network create hx

networks:
  hyperarb: 
    external: true

services:

    build: 
      context: .
      dockerfile: ops/Dockerfile
      args:
        - PROGRAM=arbitrager
        - BUILD_TYPE=debug
    depends_on: []
    environment:
      - RUST_LOG=off,shd=trace,arbitrager=trace,test=trace
    restart: always
    networks:
      - hyperarb

  manager:
    build: 
      context: .
      dockerfile: ops/DockerfileRebal
    depends_on: []
    restart: always
    depends_on: []
    networks:
      - hyperarb
