# To validate it, run: docker compose config
# docker network create hx

networks:
  hyperarb: 
    external: true

services:

  manager:
    build: 
      context: .
      dockerfile: ops/Dockerfile
      args:
        - PROGRAM=rebalancer
        - BUILD_TYPE=debug
    depends_on: []
    environment:
      - RUST_LOG=off,shd=trace,rebalancer=trace,test=trace
    restart: always
    networks:
      - hyperarb

  arbitrager:
    build: 
      context: .
      dockerfile: ops/Dockerfile
      args:
        - PROGRAM=arbitrager
        - BUILD_TYPE=debug
    depends_on: []
    environment:
      - RUST_LOG=off,shd=trace,arbitrager=trace,test=trace
    restart: always
    networks:
      - hyperarb

  # NEW: TypeScript inventory manager
  ts-manager:
    build: 
      context: .
      dockerfile: ops/Dockerfile.manager
    depends_on: []
    environment:
      - TARGET_NAME=delta              # Target selection (optional - if not set, monitors all targets)
      - CONFIG_PATH=/app/config/main.toml
      - WALLET_PUB_KEYS=${WALLET_PUB_KEYS}           # Comma-separated public keys
      - WALLET_PRIVATE_KEYS=${WALLET_PRIVATE_KEYS}   # Comma-separated private keys
    restart: always
    networks:
      - hyperarb
    volumes:
      - ./config:/app/config:ro
  